CLOUD-2752: Make isBase64Encoded optional
SunsetRiders/build-proxy-response pull request #1
Opened 2018-07-09 18:09 UTC by vinacovre

**Jira Card:** <https://vmtesdrive.atlassian.net/browse/CLOUD-2752>

## Process checklist

  - [ ] Jira Card is on Code Review (**Sprint has not yet started**)
  - [x] Assigned at least 2 mandatory reviewers on this PR
  - [x] Inform the reviewers on Slack
  - [x] This PR link is on Jira Card

## Testing checklist

  - [x] I did manual tests
  - [x] I run `npm test` with success

## CI checklist

  - [ ] I certified a green status on CI before creating the PR

## Commentaries

> I also updated node version

2018-07-09 19:16 UTC, felipe-norato approved these changes

2018-07-09 19:16 UTC, noratodaitan commented on README.md
> +This module was developed in [version 10.6](https://nodejs.org/en/blog/release/v10.6.0/) of [Node.js](https://nodejs.org/en/), we recommend that you install it using [Node Version Manager (`nvm`)](ht
we set node `node 10.5` in front-end. Are you sure you`ll set this version?

2018-07-09 19:23 UTC, vinacovre commented on README.md
> +This module was developed in [version 10.6](https://nodejs.org/en/blog/release/v10.6.0/) of [Node.js](https://nodejs.org/en/), we recommend that you install it using [Node Version Manager (`nvm`)](ht
Not so sure. However, it is the latest stable one (see https://nodejs.org/en/)

2018-07-11 12:54 UTC, msz-dev requested changes

2018-07-11 12:54 UTC, msz-dev commented on index.js
> +const buildProxyResponse = (statusCode = 500, body, isBase64Encoded = false) => {
Please, leave the optional arguments to the right, like that: `body, statusCode = 500, isBase64Encoded = false`.

2018-07-11 13:18 UTC, msz-dev approved these changes

2018-07-11 14:04 UTC, merged